<a href="https://colab.research.google.com/github/Cris-19-77-99/Opti_no_lineal/blob/main/gradiente_conjugado_hestenes_stiefel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


def f(v):
  return (v[0]-4)**4+(v[1]-3)**2+4*(v[2]+5)**4


def df(v):
  return np.array([4*(v[0]-4)**3,2*(v[1]-3),16*(v[2]+5)**3])


def mdsec(y0,y1,df_f,c=0):
  f0=df_f(y0)
  f1=df_f(y1)
  if abs(f1-f0)<10**(-12) or c>=100:
    return y1
  y2=y1-((y1-y0)/(f1-f0))*f1
  if abs(df_f(y2))<10**(-5):
    return y2
  else:
    return mdsec(y1,y2,df_f,c+1)


def fc(f,df,x0,d0,c):
  g0=df(x0)
  if np.linalg.norm(g0)<10**(-5) or c>=100:
    return x0,c
  else:
    print(x0)
    def df_a(a):
      return np.dot(df(x0+a*d0),d0)
    a=mdsec(-2,2,df_a)
    x1=x0+a*d0
    g1=df(x1)
    if np.linalg.norm(g1)<10**(-5):
      return x1,c+1
    else:
      diferencia=g1-g0
      denominador=np.dot(d0,diferencia)
      if abs(denominador)<10**(-12):
        b=0
      else:
        b=max(0,np.dot(g1,diferencia)/denominador)
      d1=-g1+b*d0
      return fc(f,df,x1,d1,c+1)


x0=np.array([4.0,2.0,1.0])
resultado=fc(f,df,x0,-df(x0),0)

print("Resultado:")
print(resultado)
print("Valor de la función:")
print(f(resultado[0]))
print("Norma del gradiente:")
print(np.linalg.norm(df(resultado[0])))

[4. 2. 1.]
[ 4.          2.00349631 -5.04161805]
[ 4.          3.         -5.04161603]
[ 4.          3.         -5.02763052]
[ 4.          3.         -5.01840569]
[ 4.          2.99999994 -5.01226854]
[ 4.          3.00001726 -5.00819911]
[ 4.          2.99999274 -5.00815812]
Resultado:
(array([ 4.        ,  3.00000003, -5.00543833]), 8)
Valor de la función:
3.4988380193956475e-09
Norma del gradiente:
2.5743537229158462e-06
