<a href="https://colab.research.google.com/github/Cris-19-77-99/Opti_no_lineal/blob/main/SEC%2CFC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import sympy as sp
import math

def f(v):
  return (v[0]-4)**(4)+(v[1]-3)**(2)+4*(v[2]+5)**(4)
def df(v):
  return np.array([[4*((v[0]-4)**3)],[2*(v[1]-3)],[16*((v[2]+5)**3)]])
def mdsec(y0,y1,df_f):
  y2= y1-((y1-y0)/(df_f(y1)-df_f(y0)))*df_f(y1)

  if df_f(y2) < 10**(-5):
    return (y2)

  else:
    return(mdsec(y1,y2,df_f))


def fc(f,df,x0,d0,c):
  c=c+1
  if math.sqrt((df(x0)[0])**2+(df(x0)[1])**2+(df(x0)[2])**2)< 10**(-5):
    return (x0,c)
  else:
    print(x0)
    def df_a(z):
      x = sp.Symbol('x')
      fun=f(x0+np.transpose(x*d0)[0])
      f_prime=fun.diff(x)
      f_prime = sp.lambdify(x, f_prime)
      return(f_prime(z))
    print(df_a(2))
    a= mdsec(-2,2,df_a)
    x1=(x0+np.transpose(a*d0))[0]
    if math.sqrt((df(x1)[0])**2+((df(x1)[1])**2+(df(x1)[2])**2))< 10**(-5):
      return (x1,c)
    else:
      b= max(0,((np.transpose(df(x1))@(df(x1)-df(x0)))/(np.transpose(d0)@(df(x1)-df(x0))))[0])
      d1= -df(x1)+b*d0
      return(fc(f,df,x1,d1,c))
fc(f,df,np.array([4,2,1]),-df(np.array([4,2,1])),0)

/tmp/ipykernel_1007/2423267523.py:21: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  if math.sqrt((df(x0)[0])**2+(df(x0)[1])**2+(df(x0)[2])**2)< 10**(-5):


[4 2 1]
18212662448603148
[ 4.          2.00349631 -5.04161805]
11.916244602606422
[ 4.          3.         -5.04161603]
-1.1207777086042135e-06
[ 4.          3.         -5.02763052]
-1.0576677516454172e-07
[ 4.          3.         -5.01840569]
-9.632777392194235e-09
[ 4.          2.99999994 -5.01226854]
-8.603642201879576e-10
[ 4.          3.00001726 -5.00819911]
3.039831289243136e-09
[ 4.          2.99999274 -5.00815812]
-2.795604627319996e-10


/tmp/ipykernel_1007/2423267523.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  if math.sqrt((df(x1)[0])**2+((df(x1)[1])**2+(df(x1)[2])**2))< 10**(-5):
/tmp/ipykernel_1007/2423267523.py:21: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  if math.sqrt((df(x0)[0])**2+(df(x0)[1])**2+(df(x0)[2])**2)< 10**(-5):


(array([ 4.        ,  3.00000003, -5.00543833]), 8)